### ISSUE TITLE
Scroll to recently added item

### ISSUE THREAD

**Issue by hrabkin** [Mehmetyaz/dashboard#15]
Hello
When a dashboard layout is filled tight by items and a new item is added it's usually placed at the bottom of the dashboard. Its not evident to a user that the new item was successfully added therefore I wanted to add simple animated scrolling to the added item when adding completes but I can't figure out how to get item's position/offset for scrolling. 

I see that there's some private property called `ItemCurrentPosition` in `DashboardItemWidget` which looks like encapsulates coordinate-related stuff of dashboard's item placement but can't find any public access to it.

Could you navigate me how to do this correctly?

```
double offset = 0;
_scrollController.animateTo(offset, duration: const Duration(milliseconds: 400), curve: Curves.easeIn);
```

**Comment by Mehmetyaz** [comment]
Done #31
