### ISSUE TITLE
How do I increase the number of grids？

### ISSUE THREAD

**Issue by TangStudio** [Mehmetyaz/dashboard#2]
Now the slot parameter can only be one of 4, 6, or 8. Simply increasing the value of slotAspectRatio does not change the number of horizontal grids. I want an application that can run on a large screen. thank you

**Comment by Mehmetyaz** [comment]
No, slotCount can be any positive integer. (Of course less is preferable. The number of slots affects performance.). I just used these numbers in the example. Using `slotCount` and `slotAspectRatio` (or slotHeight), you can freely adjust the number and size of slots, both horizontally and vertically.
