### ISSUE TITLE
Dashboard item position is not set when we call the dashboard item data from the firebase

### ISSUE THREAD

**Issue by MuhammadSherdil** [Mehmetyaz/dashboard#33]
try {
      final itemData = await FireStoreDBServices.getConfiguration(
          AuthServices.auth.currentUser!.email!);
      dashboardItemData = DashboardItemData.fromJson(itemData);
      dashboardItemController.clear();

      for (final value in dashboardItemData.configuration!) {
        dashboardItemController.add(DashboardItem(
            width: value.width!,
            height: value.height!,
            startY: value.startX!,
            startX: value.startY!,
            identifier: value.identifier!,
           ),mountToTop: false,)
        ;
      }
      loading = false;
      notifyListeners();
    } on Exception catch (e) {
      loading = false;
      error = e.toString();
      notifyListeners();
    }
the position x and y is not set in the dashboard here is the data from database:
{
configuration: [
{maxWidth: 5, minWidth: 4, width: 4, startX: 0, minHeight: 3, identifier: barChart 0, height: 3, maxHeight: 4, startY: 0}, 
{startY: 0, startX: 4, maxHeight: 4, maxWidth: 5, minHeight: 3, identifier: gauges 1, width: 4, minWidth: 4, height: 3},
 {minWidth: 4, identifier: slider 2, maxWidth: 5, width: 4, minHeight: 2, height: 2, startX: 8, maxHeight: 3, startY: 0}, {startY: 4, startX: 1, maxWidth: 5, maxHeight: 4, height: 3, minWidth: 4, identifier: barChart 3, width: 4, minHeight: 3}
]},
![Cloud IOT Services - Google Chrome 12_4_2023 12_17_41 PM](https://github.com/Mehmetyaz/dashboard/assets/144653806/2fa68795-02bf-4ada-80c5-79d03846a410)
as show in this image it is not set the position of dashboard item according to x and y position, how we will manage it please explain

**Comment by MuhammadSherdil** [comment]
@Mehmetyaz @rohanjariwala03 @yazmehmet  do you have any solution for this problem?

**Comment by Mehmetyaz** [comment]
The data and screenshot seem to match. I didn't understand what the problem was.

Here I briefly explained how the layout works. I hope it helps.

![image](https://github.com/Mehmetyaz/dashboard/assets/48976445/537834f0-577c-464a-9423-f46ca1d91e00)

**Comment by MuhammadSherdil** [comment]
![Cloud IOT Services - Profile 1 - Microsoft​ Edge 12_4_2023 5_46_54 PM](https://github.com/Mehmetyaz/dashboard/assets/144653806/bbc61d94-9526-46b9-8876-f90a4a45de9a)
as show in this image i am saving the height and width and x and y position of dashboard item in firestore database.
when i retrieve the data of dashbaord item then it will give me this.
![Cloud IOT Services - Profile 1 - Microsoft​ Edge 12_4_2023 5_49_50 PM](https://github.com/Mehmetyaz/dashboard/assets/144653806/1d1fd79a-b3ae-4ed7-8dae-2b1e3dd929b7)
so my question is that how we will manage the size and position of dashboard item when we get the data from an external db.

**Comment by MuhammadSherdil** [comment]
i want the same item position as we set it on item saving dashboard and item display dashboard. can you please elaborate this.

**Comment by Mehmetyaz** [comment]
First of all, if there are gaps in the layout coming from the database, the dashboard automatically fills them. If you want to turn off this feature, you need to set the `slideToTop` argument to false.


Coming to the main issue:

If you are asking how users can edit the items: After placing the Dashboard items, you need to turn on the edit mode to allow changing the dimensions, as you can see in the example. After Edit mode is turned on, users can change the size / location of the items. You must define a DashboardItemStorageDelegate to listen for these changes. There you can read the changes made by users with onItemsUpdated.

```dart
IconButton(
    onPressed: () {
       itemController.isEditing = !itemController.isEditing;
        setState(() {});
    },
    icon: const Icon(Icons.edit)
)
```

```dart
IconButton(
    onPressed: () {
       itemController.isEditing = !itemController.isEditing;
        setState(() {});
    },
    icon: const Icon(Icons.edit)
)
```

**Comment by Mehmetyaz** [comment]
Are you okey ? @MuhammadSherdil

**Comment by MuhammadSherdil** [comment]
okay sir, let me implement as you say.
