### ISSUE TITLE
the item is not set on y position

### ISSUE THREAD

**Issue by MuhammadSherdil** [Mehmetyaz/dashboard#34]
the item place is not change on y position. as shown in this video. how to resolve that

https://github.com/Mehmetyaz/dashboard/assets/144653806/e3b784ea-f3e1-43b0-b4df-959b931a7d25

**Comment by MuhammadSherdil** [comment]
@Mehmetyaz  can you please help me on that?

**Comment by MuhammadSherdil** [comment]
Dashboard(
                        itemBuilder: (item) {
                          if (provider.dashboardItemController.items.isNotEmpty &&
                              item.identifier != "nothing") {
                            final splitItem = item.identifier.split(" ");
                            final widgetType = splitItem[0];
                            final id = splitItem[1];
                            print(
                                "x:${item.layoutData.startX} : y: ${item.layoutData.startY}");
                            provider.dashboardItemData
                                    .configuration?[int.parse(id)] =
                                Configuration(
                                    height: item.layoutData.height,
                                    width: item.layoutData.width,
                                    identifier: item.identifier,
                                    startX: item.layoutData.startX,
                                    startY: item.layoutData.startY,
                                    maxHeight: item.layoutData.maxHeight,
                                    minHeight: item.layoutData.minHeight,
                                    maxWidth: item.layoutData.maxWidth,
                                    minWidth: item.layoutData.minWidth);

                            if (widgetType == "slider") {
                              return DashboardCustomSlider(
                                id: id,
                                itemId: item.identifier,
                              );
                            } else if (widgetType == "switch") {
                              return DashboardCustomSwitch(
                                id: id,
                                itemId: item.identifier,
                              );
                            } else if (widgetType == "barChart") {
                              return DashboardCustomBarChart(
                                id: id,
                                itemId: item.identifier,
                              );
                            } else if (widgetType == "gauges") {
                              return DashboardCustomGauges(
                                id: id,
                                itemId: item.identifier,
                              );
                            } else {
                              return Container();
                            }
                          } else {
                            return const Text(
                              "nothing",
                              style: TextStyle(color: Colors.transparent),
                            );
                          }
                        },
                        scrollController: scrollController,
                        scrollBehavior: const MaterialScrollBehavior(),
                        physics: const AlwaysScrollableScrollPhysics(),dragStartBehavior: DragStartBehavior.down,

                        slotBackgroundBuilder: SlotBackgroundBuilder.withFunction(
                            (context, item, x, y, editing) {
                          return Container(
                            decoration: BoxDecoration(
                              color: Colors.white12,
                              border:
                                  Border.all(color: Colors.white12, width: 0.5),
                              borderRadius: BorderRadius.circular(20),
                            ),
                          );
                        }),
                        shrinkToPlace: true,
                        slideToTop: false,
                        emptyPlaceholder: Container(),
                        itemStyle: ItemStyle(
                          borderRadius: BorderRadius.circular(20),
                          shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(20)),
                          color: isDashboardInit
                              ? Colors.transparent
                              : ColorName.appThemeColor.shade400,

                            shadowColor: Colors.black,
                            animationDuration: const Duration(milliseconds: 200),
                            borderOnForeground: false,
                            clipBehavior: Clip.antiAliasWithSaveLayer,
                            elevation: 10,
                            textStyle: const TextStyle(color: Colors.black),
                            type: MaterialType.card
                        ),
                        absorbPointer: false,
                        dashboardItemController: provider.dashboardItemController,
                        padding: const EdgeInsets.all(20),
                        slotCount: 12,
                        animateEverytime: true,
                        slotAspectRatio: 1,
                        verticalSpace: 10,scrollToAdded: true,

                        editModeSettings: EditModeSettings(
                      draggableOutside: true,
                            fillEditingBackground: true,
                            shrinkOnMove: true,
                            panEnabled: true,
                            curve: Curves.easeIn,
                            paintBackgroundLines: true,
                            resizeCursorSide: 10,
                            autoScroll: false,
                            longPressEnabled: true,
                            backgroundStyle: const EditModeBackgroundStyle(
                              dualLineVertical: false,
                              dualLineHorizontal: false,
                            )),
                      )
 here is the example  dashboard widget code that i have used.

**Comment by yazmehmet** [comment]
Hi. Can you downgrade and try again?  First, I want to understand whether the problem is related to the update or not.

**Comment by MuhammadSherdil** [comment]
Same issue on 0.0.3+1
`import 'package:cloud_iot_service/gen/assets.gen.dart';
import 'package:cloud_iot_service/gen/colors.gen.dart';
import 'package:cloud_iot_service/model/dashboard_item_model.dart';
import 'package:cloud_iot_service/provider/template_provider.dart';
import 'package:cloud_iot_service/view/pages/admin/home_page/pages/template_page/template_widgets/dashboard_custom_bar_chart.dart';
import 'package:cloud_iot_service/view/pages/admin/home_page/pages/template_page/template_widgets/dashboard_custom_gauges.dart';
import 'package:cloud_iot_service/view/widgets/custom_button_widget.dart';
import 'package:cloud_iot_service/view/widgets/custom_scaffold_widget.dart';
import 'package:dashboard/dashboard.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:provider/provider.dart';
import 'template_widgets/dashboard_custom_switch.dart';
import 'template_widgets/dashboard_custom_slider.dart';

class TemplatePage extends StatefulWidget {
  const TemplatePage({super.key, required this.email});
  final String email;
  @override
  State<TemplatePage> createState() => _TemplatePageState();
}

class _TemplatePageState extends State<TemplatePage>
    with SingleTickerProviderStateMixin {
  bool openContainer = false;
  ScrollController scrollController = ScrollController();
  late AnimationController animationController;
  late Animation<double> iconAnimation;
  bool isDashboardInit = false;
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    animationController = AnimationController(
        vsync: this, duration: const Duration(milliseconds: 500));
    iconAnimation =
        Tween<double>(begin: 0, end: 1).animate(animationController);
    Future.delayed(Duration.zero, () {
      Provider.of<TemplateProvider>(context, listen: false);
    });

    setState(() {
      isDashboardInit = true;
    });
  }

  @override
  void dispose() {
    animationController.dispose();
    scrollController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final size = MediaQuery.of(context).size;
    return Consumer<TemplateProvider>(builder: (context, provider, _) {
      return CustomScaffoldWidget(
        appBar: AppBar(
          backgroundColor: ColorName.appThemeColor,
          actions: [
            CustomButtonWidget(
                btnText: "Save",
                onPressed: () {
                  provider.addConfiguration(widget.email);
                },
                size: const Size(100, 50))
          ],
        ),
        body: Row(
          children: [
            AnimatedContainer(
              height: size.height,
              width: openContainer ? size.width / 4 : 0,
              color: Colors.indigo.shade200,
              curve: Curves.linear,
              padding: const EdgeInsets.only(top: 30, left: 10, right: 10),
              duration: const Duration(milliseconds: 500),
              child: FadeTransition(
                opacity: iconAnimation,
                child: ListView.builder(
                    itemCount: widgetDataList.length,
                    shrinkWrap: true,
                    itemBuilder: (context, int index) {
                      return Padding(
                        padding: const EdgeInsets.only(bottom: 10),
                        child: Draggable<WidgetDataModel>(
                            feedback: Material(
                                borderRadius: BorderRadius.circular(20),
                                child: SizedBox(
                                  width: size.width / 4.5,
                                  height:
                                      widgetDataList[index].columnCount * 50,
                                  child: Center(
                                    child: SvgPicture.asset(
                                      widgetDataList[index].image,
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                )),
                            onDraggableCanceled: (a, b) {
                              if (kDebugMode) {
                                print("Cancelled");
                              }
                            },
                            childWhenDragging: SizedBox(
                              width: size.width / 4.5,
                              height: widgetDataList[index].columnCount * 50,
                              child: SvgPicture.asset(
                                widgetDataList[index].image,
                                fit: BoxFit.fill,
                              ),
                            ),
                            data: widgetDataList[index],
                            child: SizedBox(
                              width: size.width / 4.5,
                              height: widgetDataList[index].columnCount * 50,
                              child: SvgPicture.asset(
                                widgetDataList[index].image,
                                fit: BoxFit.fill,
                              ),
                            )),
                      );
                    }),
              ),
            ),
            IconButton(
                onPressed: () => setState(() {
                      openContainer = !openContainer;
                      if (openContainer) {
                        animationController.forward();
                        provider.dashboardItemController.isEditing = true;

                        if (isDashboardInit) {
                          provider.dashboardItemController.clear();
                          isDashboardInit = false;
                        }
                      } else {
                        animationController.reverse();
                        provider.dashboardItemController.isEditing = false;
                      }
                    }),
                icon: AnimatedIcon(
                    icon: AnimatedIcons.list_view,
                    color: Colors.white,
                    progress: animationController)),
            Expanded(
                flex: 2,
                child: DragTarget<WidgetDataModel>(
                  onAccept: (value) {
                    final id =
                        "${value.id} ${provider.dashboardItemController.items.length.toString()}";
                    final DashboardItem dashBoardItem = DashboardItem(
                        width: value.columnCount,
                        height: value.rowCount,
                        minHeight: value.minHeight ?? value.rowCount,
                        maxHeight: value.maxHeight ?? value.rowCount + 1,
                        minWidth: value.minWidth ?? value.columnCount,
                        maxWidth: value.maxWidth ?? value.columnCount + 1,
                        startX: value.xAxis,
                        startY: value.yAxis,
                        identifier: id);
                    provider.dashboardItemData.configuration?.add(Configuration(
                        width: value.columnCount,
                        height: value.rowCount,
                        minHeight: value.minHeight ?? value.rowCount,
                        maxHeight: value.maxHeight ?? value.rowCount + 1,
                        minWidth: value.minWidth ?? value.columnCount,
                        maxWidth: value.maxWidth ?? value.columnCount + 1,
                        startX: value.xAxis,
                        startY: value.yAxis,
                        identifier: id));
                    provider.dashboardItemController.add(
                      dashBoardItem,
                      mountToTop: false,
                    );
                  },
                  builder: (BuildContext context,
                      List<WidgetDataModel?> candidateData,
                      List<dynamic> rejectedData) {
                    return Dashboard(
                      itemBuilder: (item) {
                        return buildItems(provider, item);
                      },
                      scrollController: scrollController,

                      scrollBehavior: const MaterialScrollBehavior(),
                      physics: const AlwaysScrollableScrollPhysics(),
                      dragStartBehavior: DragStartBehavior.start,
                      slotBackgroundBuilder: SlotBackgroundBuilder.withFunction(
                          (context, item, x, y, editing) {
                        return Container(
                          decoration: BoxDecoration(
                            color: Colors.white12,
                            border:
                                Border.all(color: Colors.white12, width: 0.5),
                            borderRadius: BorderRadius.circular(20),
                          ),
                        );
                      }),
                      shrinkToPlace: false,
                      slideToTop: false,
                      errorPlaceholder: (e, s) {
                        return Text("$e , $s");
                      },
                      emptyPlaceholder: const Center(child: Text("Empty")),
                      itemStyle: ItemStyle(
                          borderRadius: BorderRadius.circular(20),
                          shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(20)),
                          color: isDashboardInit
                              ? Colors.transparent
                              : ColorName.appThemeColor.shade400,
                          shadowColor: Colors.black,
                          animationDuration: const Duration(milliseconds: 200),
                          borderOnForeground: false,
                          clipBehavior: Clip.antiAliasWithSaveLayer,
                          elevation: 10,
                          textStyle: const TextStyle(color: Colors.black),
                          type: MaterialType.card),
                      absorbPointer: false,
                      dashboardItemController: provider.dashboardItemController,
                      padding: const EdgeInsets.all(20),
                      slotCount: 12,
                      animateEverytime: true,
                      slotAspectRatio: 1,
                      verticalSpace: 10,
                      scrollToAdded: true,
                      editModeSettings: EditModeSettings(
                          fillEditingBackground: true,
                          shrinkOnMove: false,
                          panEnabled: true,
                          curve: Curves.easeIn,
                          paintBackgroundLines: false,
                          resizeCursorSide: 10,
                          autoScroll: true,
                          longPressEnabled: false,
                          backgroundStyle: const EditModeBackgroundStyle(
                            dualLineVertical: false,
                            dualLineHorizontal: false,
                          )),
                    );
                  },
                )),
          ],
        ),
      );
    });
  }

  Widget buildItems(TemplateProvider provider, DashboardItem item) {
    if (provider.dashboardItemController.items.isNotEmpty &&
        item.identifier != "nothing") {
      final splitItem = item.identifier.split(" ");
      final widgetType = splitItem[0];
      final id = splitItem[1];
      if (kDebugMode) {
        print("x:${item.layoutData.startX} : y: ${item.layoutData.startY}");
      }
      provider.dashboardItemData.configuration?[int.parse(id)] = Configuration(
          height: item.layoutData.height,
          width: item.layoutData.width,
          identifier: item.identifier,
          startX: item.layoutData.startX,
          startY: item.layoutData.startY,
          maxHeight: item.layoutData.maxHeight,
          minHeight: item.layoutData.minHeight,
          maxWidth: item.layoutData.maxWidth,
          minWidth: item.layoutData.minWidth);

      if (widgetType == "slider") {
        return DashboardCustomSlider(
          id: id,
          itemId: item.identifier,
        );
      } else if (widgetType == "switch") {
        return DashboardCustomSwitch(
          id: id,
          itemId: item.identifier,
        );
      } else if (widgetType == "barChart") {
        return DashboardCustomBarChart(
          id: id,
          itemId: item.identifier,
        );
      } else if (widgetType == "gauges") {
        return DashboardCustomGauges(
          id: id,
          itemId: item.identifier,
        );
      } else {
        return Container();
      }
    } else {
      return const Text(
        "nothing",
        style: TextStyle(color: Colors.transparent),
      );
    }
  }

  final List<WidgetDataModel> widgetDataList = [
    WidgetDataModel(
        image: Assets.images.demoSlider.path,
        columnCount: 4,
        rowCount: 2,
        xAxis: 0,
        yAxis: 0,
        id: "slider"),
    WidgetDataModel(
        image: Assets.images.demoSwitch.path,
        columnCount: 3,
        rowCount: 2,
        xAxis: 0,
        yAxis: 0,
        id: "switch"),
    WidgetDataModel(
        image: Assets.images.demoBarChart.path,
        columnCount: 4,
        rowCount: 3,
        xAxis: 0,
        yAxis: 0,
        id: "barChart"),
    WidgetDataModel(
        image: Assets.images.demoGauge.path,
        columnCount: 4,
        rowCount: 3,
        xAxis: 0,
        yAxis: 0,
        id: "gauges"),
  ];
}

class WidgetDataModel {
  int rowCount;
  int columnCount;
  String image;
  String? id;
  int? maxWidth;
  int? minWidth;
  int? maxHeight;
  int? minHeight;
  int? xAxis;
  int? yAxis;

  WidgetDataModel({
    required this.image,
    this.id,
    this.xAxis,
    this.yAxis,
    this.maxWidth,
    this.minWidth,
    this.maxHeight,
    this.minHeight,
    required this.columnCount,
    required this.rowCount,
  });
}
`

**Comment by Mehmetyaz** [comment]
I think I understand the problem.  Please let me try.  I will try to reproduce this problem myself

**Comment by MuhammadSherdil** [comment]
Sure sir

**Comment by MuhammadSherdil** [comment]
> I think I understand the problem. Please let me try. I will try to reproduce this problem myself

@Mehmetyaz @yazmehmet did you find any issue?

**Comment by mennovanhout** [comment]
Following, seems to be web only

**Comment by MuhammadSherdil** [comment]
Yes
  
  
 

 
  
 
   On Sat, Dec 16, 2023, 03:57 am Menno van Hout ***@***.***> wrote: 
   
  
  
   
  Following, seems to be web only 
  —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> 
  [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Mehmetyaz/dashboard/issues/34#issuecomment-1858585738",
"url": "https://github.com/Mehmetyaz/dashboard/issues/34#issuecomment-1858585738",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by sherdiltahir** [comment]
> Following, seems to be web only

Yes it is

**Comment by mennovanhout** [comment]
@Mehmetyaz Do you need any help?

**Comment by dsyrstad** [comment]
@Mehmetyaz @yazmehmet Looks like this is the problem: https://github.com/Mehmetyaz/dashboard/blob/415a6d5316cefacc39905acece7717bba579bfe6/lib/src/models/item_current_layout.dart#L777

The problem is that `1 << 32` equals zero with the Dart generated javascript (really a JS limitation). If I substitute the literal value `4294967296`, it solves the issue.

**Comment by Mehmetyaz** [comment]
It's solved

**Comment by nctune2808** [comment]
> @Mehmetyaz @yazmehmet Looks like this is the problem:
> 
> https://github.com/Mehmetyaz/dashboard/blob/415a6d5316cefacc39905acece7717bba579bfe6/lib/src/models/item_current_layout.dart#L777
> 
> The problem is that `1 << 32` equals zero with the Dart generated javascript (really a JS limitation). If I substitute the literal value `4294967296`, it solves the issue.

Hi @dsyrstad, @Mehmetyaz 
I try this solution `1 << 31` instead of `1 << 32` for Web Platform, but I am not sure what is the difference between `2147483648` and `4294967296`. I guess because of 32bit and 64bit? Does it matter with the Linux Platform (Embedded Device)?

![Screenshot 2024-04-01 at 20 42 14](https://github.com/Mehmetyaz/dashboard/assets/27118779/3abb0b8d-3774-4b2f-ac95-00291cd117c1)

**Comment by dsyrstad** [comment]
> Hi @dsyrstad, @Mehmetyaz I try this solution `1 << 31` instead of `1 << 32` for Web Platform, but I am not sure what is the difference between `2147483648` and `4294967296`. I guess because of 32bit and 64bit? Does it matter with the Linux Platform (Embedded Device)?

@nctune2808 It's because the limitations of numeric operations in Javascript (mentioned here https://github.com/Mehmetyaz/dashboard/issues/34#issuecomment-1901304406 and here https://dart.dev/guides/language/numbers#bitwise-operations).  

It's not an issue running under the Linux platform.
