### ISSUE TITLE
StartX and StartY not assigned after Dashboard is created

### ISSUE THREAD

**Issue by rohanjariwala03** [Mehmetyaz/dashboard#7]
**Issue**
- Adding new colour widget with startX and startY with the help of + button. It's adding the widget but always adding at the top not at the place of startX and startY (Making startX and startY to 0).

**How you can reproduce this issue?**
- You can add 2 more fields (startX and starY) in the addDialogBox. And assign startX and startY to the ColoredDashboardItem class while adding them to the itemController.

![image](https://user-images.githubusercontent.com/34390549/207714378-587bffcc-8585-4b54-ae42-a06dc08768bb.png)

**Comment by Mehmetyaz** [comment]
Thanks to your issue. 

I added a `mountToTop` parameter to the `add` and `addAll` methods. If you set it to false it will try to insert it starting from the `startX` and `startY` you provided. It will never try to place before the starting points you give.

`mountToTop` default is `true`.

**Comment by dsyrstad** [comment]
@Mehmetyaz Unfortunately, `mountToTop` isn't available if you use a storage delegate and want to save and restore startX and startY so the state is restored as it appeared originally. Returning these values from a storage delegate doesn't have an effect - it just lays the widgets out left-to-right, top-to-bottom. I have `slideToTop` set to false.
